"""One-time static source preparation. Build never executes this script.
Artwork is extracted only from clean image regions; UI remains editable HTML.
"""
from pathlib import Path
from PIL import Image, ImageDraw
from html import escape
import json, shutil

ROOT=Path(__file__).resolve().parents[1]
ASSETS=ROOT/'assets/images/sections'
ASSETS.mkdir(parents=True,exist_ok=True)
records=[]
def e(s):return escape(str(s),quote=True)
def ic(name):return f'<i class="fa-solid fa-{name}" aria-hidden="true"></i>'
def a(text,cls=''):return f'<a href="#" class="{cls}">{text}</a>'
def btn(text,label=None,cls=''):return f'<button type="button" class="{cls}"'+(f' aria-label="{e(label)}"' if label else '')+f'>{text}</button>'
def crop(n,name,box,clean_badge=False):
    source=Image.open(ROOT/f'design/section-{n}.png').convert('RGB')
    box=tuple(round(v) for v in box)
    result=source.crop(box)
    if clean_badge:
        # The selected image area overlaps only the empty corner under a UI badge.
        ImageDraw.Draw(result).rectangle((0,0,min(52,result.width//4),26),fill='white')
    path=ASSETS/f's{n}-{name}.webp'
    result.save(path,quality=94)
    records.append({'section':n,'asset':str(path.relative_to(ROOT)).replace('\\','/'),'source':f'design/section-{n}.png','crop':box,'size':result.size,'cleanup':'white empty top-left badge corner' if clean_badge else None})
    return str(path.relative_to(ROOT)).replace('\\','/')
def img(path,alt='',cls=''):
    w,h=Image.open(ROOT/path).size
    return f'<img src="{path}" width="{w}" height="{h}" alt="{e(alt)}" class="{cls}" loading="lazy" decoding="async">'
def heading(n,title,desc='',eyebrow=''):
    return f'<div class="hs-heading">'+(f'<p class="hs-eyebrow">{eyebrow}</p>' if eyebrow else '')+f'<h1 id="s{n}-title" data-section-heading>{title}</h1>'+ (f'<p>{desc}</p>' if desc else '')+'</div>'
def write(n,body,accent='#ed0028',extra='',dark=False):
    tag='footer' if n==25 else 'section'
    html=f'<{tag} id="section-{n}" class="section-{n} hacom-section {extra}" style="--accent:{accent}" aria-labelledby="s{n}-title">\n<div class="hacom-container hs-shell">\n{body}\n</div>\n</{tag}>\n'
    # Keep static section source easy to inspect and edit without a framework.
    html=html.replace('><','>\n<')
    (ROOT/f'src/sections/section-{n}.html').write_text(html,encoding='utf-8')
def benefits(items,icons=None):
    icons=icons or ['truck-fast','shield-halved','headset','gift','gear','award']
    return '<ul class="hs-benefits">'+''.join('<li>'+ic(icons[i%len(icons)])+'<span>'+t+'</span></li>' for i,t in enumerate(items))+'</ul>'
def strip(items,cta='Khám phá ngay',intro='Khám phá thêm',sub='Đội ngũ chuyên gia HACOM luôn sẵn sàng hỗ trợ'):
    return '<div class="hs-strip"><div class="hs-strip-intro">'+ic('gift')+f'<span><strong>{intro}</strong><small>{sub}</small></span></div><div class="hs-strip-items">'+''.join(a(ic(['shield-halved','gear','headset','cube'][i%4])+'<span>'+t+'</span>') for i,t in enumerate(items))+'</div>'+a(cta+' '+ic('arrow-right'),'hs-cta')+'</div>'
def filters(items,label='Xem tất cả sản phẩm'):
    return '<nav class="hs-filters" tabindex="0" aria-label="Nhóm sản phẩm"><div>'+''.join(a((ic('fire')+' ' if i==0 else '')+t,'is-selected' if i==0 else '') for i,t in enumerate(items))+'</div>'+a(label+' '+ic('arrow-right'),'hs-viewall')+'</nav>'
def category_tiles(n,names,box,columns=8):
    x1,y1,x2,y2=box; step=(x2-x1)/columns
    return '<div class="hs-categories" tabindex="0" aria-label="Danh mục">'+''.join(a(img(crop(n,f'category-{i+1}',(x1+i*step+9,y1,x1+(i+1)*step-9,y2)),name)+f'<span>{name}</span>') for i,name in enumerate(names))+'</div>'
def brandrow(brands):
    out=[]
    branddir=ROOT/'assets/images/brands';branddir.mkdir(exist_ok=True)
    for i,name in enumerate(brands):
        origin=Path('D:/hacom-0309/assets/images/branding')/(name.lower()+'.webp')
        if origin.exists():
            target=branddir/origin.name;shutil.copyfile(origin,target);content=img(str(target.relative_to(ROOT)).replace('\\','/'),name)
        else:content=f'<strong>{e(name)}</strong>'
        out.append(a(content,'is-selected' if i==0 else ''))
    return '<div class="hs-brands" tabindex="0" aria-label="Thương hiệu">'+''.join(out)+'</div>'
def callout(title,desc,cta='Khám phá ngay'):
    return '<div class="hs-callout">'+ic('microchip')+f'<span><strong>{title}</strong><small>{desc}</small></span>'+a(cta+' '+ic('arrow-right'),'hs-white-button')+'</div>'
def productrail(n,products,geometry,trade=False,horizontal=False,ratings=True):
    x,step,y1,y2=geometry;cards=[]
    for i,p in enumerate(products):
        name,spec,price,old,rating,badge=p
        # Crop product artwork only, excluding title/price/button/heart areas.
        image=crop(n,f'product-{i+1}',(x+i*step+10,y1,x+i*step+125,y2) if horizontal else (x+i*step+60,y1,x+(i+1)*step-60,y2),clean_badge=not horizontal)
        cards.append('<article class="hs-product">'+('<span class="hs-product-badge">'+badge+'</span>' if badge else '')+btn(ic('heart'),f'Yêu thích {name}','hs-heart')+img(image,name,'hs-product-image')+'<div class="hs-product-copy"><h3>'+e(name)+'</h3><p class="hs-product-spec">'+e(spec)+'</p><div class="hs-product-bottom"><div><strong class="hs-price">'+price+'</strong>'+('<del>'+old+'</del>' if old else '')+('<p class="hs-rating"><span>★</span> '+rating+'</p>' if ratings and rating else '')+'</div>'+btn((ic('cart-shopping')+' Đổi ngay') if trade else ic('cart-shopping'),f'{"Đổi ngay" if trade else "Thêm vào giỏ"}: {name}','hs-cart')+'</div>'+('<small class="hs-installment">Trả góp 0% từ '+['2.749.000','2.499.000','3.082.000','2.249.000','3.749.000','2.416.000'][i%6]+'đ/tháng</small>' if n==5 else '')+'</div></article>')
    return f'<div class="hs-products {"hs-horizontal-products" if horizontal else ""}" style="--product-count:{len(products)}" tabindex="0" aria-label="Danh sách sản phẩm">'+''.join(cards)+'</div>'

# Chapter data transcribed from the supplied screenshots; duplicate labels retained.
CHAPTERS={
5:dict(ch='01',topic='LAPTOP - MACBOOK - TABLET',title='SẴN SÀNG<br>CHO <em>AI.</em>',desc='Không chỉ là laptop. Đó là trợ lý AI đồng hành trong công việc, học tập và sáng tạo.',accent='#155ce5',hero=(480,17,1163,377),brands=['ASUS','MSI','Lenovo','HP','Dell','Acer','Apple','Microsoft Surface'],cats=['Laptop Văn Phòng','Laptop Gaming','Laptop AI','Laptop Đồ Họa','Macbook & Apple','Surface','Tablet','Phụ Kiện Laptop'],catbox=(1190,222,1995,303),call='Copilot+ PC thế hệ mới đã có mặt tại HACOM',calldesc='Hiệu suất cao hơn. Thông minh hơn. Sáng tạo hơn.',tabs=['Bán chạy','Laptop AI','Gaming','Văn phòng','Văn phòng','Macbook','Surface','Tablet','Mới về'],geom=(42,333,454,540),items=[('ASUS ROG Strix G16 2024','i7-13650HX | 16GB | 1TB SSD | RTX 4060','32.990.000đ','48.990.000đ','4.8 (128)','Bán chạy #1'),('Lenovo Legion Pro 5','Ryzen 7 7745HX | 16GB | 1TB | RTX 4060','29.990.000đ','36.990.000đ','4.7 (96)','-18%'),('Dell XPS 14 9440','Ultra 7 155H | 16GB | 1TB | Intel Arc','36.990.000đ','','4.6 (74)','Mới về'),('HP OMEN 16','i7-13620H | 16GB | 1TB | RTX 4060','26.990.000đ','34.990.000đ','4.7 (88)','-22%'),('ASUS Zenbook S 14','Ultra 7 258V | 32GB | 1TB | 3K OLED','44.990.000đ','','4.9 (56)','AI PC'),('MacBook Air M3 13″','Apple M3 | 16GB | 256GB | 13.6″','28.990.000đ','33.990.000đ','4.8 (112)','-15%')],bottom=['Laptop học tập','Laptop doanh nghiệp','Laptop mỏng nhẹ','Laptop cảm ứng','2 trong 1','Laptop dưới 20 triệu'],cta='Tư vấn chọn laptop phù hợp'),
6:dict(ch='02',topic='PC - MINI PC - ALL IN ONE',title='HIỆU NĂNG<br><em>ĐƯỢC CHẾ TÁC</em>',desc='Từ gaming đến AI workstation<br>Kiến tạo sức mạnh cho mọi nhu cầu',accent='#e8002b',hero=(505,20,1162,389),brands=['HACOM Custom PC','ASUS','MSI','Dell','HP','Lenovo','Apple','Intel NUC'],cats=['PC Gaming','PC Văn Phòng','PC Đồ Họa','AI Workstation','All In One','Mini PC','Máy Trạm','Build PC theo yêu cầu'],catbox=(1190,219,1996,290),call='PC AI Workstation - Sẵn sàng cho tương lai',calldesc='Hiệu suất mạnh mẽ. Tối ưu cho AI, đồ họa và sáng tạo.',tabs=['Bán chạy','PC Gaming','PC Văn phòng','PC Đồ họa','AI Workstation','AI Workstation','All In One','Mini PC','PC Lắp Ráp'],geom=(43,332,460,542),items=[('PC HACOM Gaming Pro 5000','Intel i7-14700F | 32GB | RTX 5070 | 1TB SSD','32.990.000đ','','4.8 (128)','Bán chạy #1'),('PC Gaming ASUS ROG G700','AMD Ryzen 7 7800X3D | 32GB | RTX 5070','29.990.000đ','36.990.000đ','4.7 (96)','-18%'),('PC HACOM AI Workstation','Intel Ultra 9 285K | 64GB | RTX 5090 | 2TB','89.990.000đ','','4.9 (74)','Mới về'),('PC Đồ Họa Render Pro','AMD Ryzen 9 7950X | 64GB | RTX 4080','59.990.000đ','76.990.000đ','4.8 (56)','-22%'),('Intel NUC 14 Pro','Intel Ultra 7 | 32GB | 1TB SSD','24.990.000đ','','4.6 (42)','AI PC'),('HP All In One 27″','Intel i5-13500 | 16GB | 512GB SSD','18.990.000đ','22.490.000đ','4.7 (38)','-15%')],bottom=['PC cho Game Thủ','PC cho Nhà Sáng Tạo','PC cho Doanh Nghiệp','PC AI & Machine Learning'],cta='Nhận tư vấn cấu hình miễn phí'),
8:dict(ch='03',topic='LINH KIỆN PC',title='NÂNG CẤP<br><em>MỌI GIỚI HẠN</em>',desc='Hiệu năng mạnh mẽ.<br>Trải nghiệm vượt trội.<br>Kiến tạo dàn PC theo cách của bạn.',accent='#ff6500',hero=(465,22,1185,400),brands=[],cats=['CPU','Mainboard','VGA','RAM','SSD & HDD','PSU','Case','Tản nhiệt'],catbox=(1200,159,1995,234),call='Linh kiện chính hãng - Hiệu năng không giới hạn',calldesc='Đầy đủ CPU, VGA, RAM, SSD, Mainboard và hơn thế nữa.',tabs=['Bán chạy','CPU','Mainboard','VGA','RAM','SSD & HDD','PSU','Case','Tản nhiệt'],geom=(43,245,474,560),items=[('Intel Core i7-14700K','20C/28T | 3.4 - 5.6GHz | LGA 1700','8.990.000đ','10.990.000đ','4.8 (256)','Bán chạy #1'),('ASUS TUF B760M-PLUS WIFI D4','LGA 1700 | DDR4 | mATX','4.890.000đ','5.990.000đ','4.7 (132)','-18%'),('ASUS GeForce RTX 5080 TUF OC','16GB GDDR7 | DLSS 4 | AI Ready','36.990.000đ','46.990.000đ','4.9 (98)','-22%'),('Kingston FURY Beast DDR5','32GB (2x16GB) 6000MHz','3.990.000đ','','4.8 (75)','Mới về'),('Samsung 990 PRO 2TB','PCIe 4.0 NVMe | 7,450 MB/s','4.990.000đ','5.890.000đ','4.9 (110)','-15%'),('Corsair RM850e','850W | 80 Plus Gold | ATX 3.0','3.590.000đ','4.490.000đ','4.8 (64)','-20%'),('Lian Li LANCOOL 216','Mid Tower | RGB | ATX','2.990.000đ','','4.7 (52)','Hot'),('DeepCool LT720','360mm | AIO | ARGB','3.990.000đ','4.890.000đ','4.8 (71)','-18%')],bottom=['PC Gaming','PC Đồ họa','PC AI','PC Văn phòng'],cta='Xem tất cả linh kiện PC'),
9:dict(ch='04',topic='MÀN HÌNH - TV',title='NHÌN THẤY<br><em>MỌI CHI TIẾT</em>',desc='Màn hình thế hệ mới. Hình ảnh sống động.<br>Trải nghiệm vượt trội cho công việc, giải trí và gaming.',accent='#7b20ff',hero=(430,0,1016,390),brands=['ASUS','ASUS TUF','LG','Dell','MSI','GIGABYTE'],cats=[],catbox=None,call='MÀN HÌNH OLED - ĐỈNH CAO TRẢI NGHIỆM',calldesc='Màu sắc chân thực · Tương phản vô hạn · Lựa chọn của game thủ',tabs=['Bán chạy','Mới về','Gaming','Đồ họa','Văn phòng','TV','Màn hình cong'],geom=(81,270,456,549),items=[('Màn hình ASUS ROG Swift OLED PG27AQDM 27″ 2K 240Hz','OLED | 2K | 240Hz','18.990.000đ','25.990.000đ','4.9 (124)','-28%'),('Màn hình LG UltraGear 27GS95QE 27″ OLED 2K 240Hz','OLED | 2K | 240Hz','20.990.000đ','26.990.000đ','4.8 (86)','-22%'),('Màn hình Dell UltraSharp U2724D 27″ 2K IPS','IPS | 2K | 27″','9.990.000đ','12.190.000đ','4.7 (52)','-18%'),('Màn hình MSI MAG 274QRF 27″ 2K 180Hz IPS','IPS | 180Hz | 2K','7.490.000đ','9.990.000đ','4.8 (73)','-25%'),('Màn hình Samsung Odyssey G6 27″ 2K 240Hz','27″ | 2K | 240Hz','9.990.000đ','12.490.000đ','4.7 (68)','-20%'),('Màn hình Gigabyte M27Q 27″ 2K 170Hz IPS','IPS | 170Hz | 2K','6.990.000đ','8.390.000đ','4.8 (91)','-17%'),('Màn hình LG 32UR500 32″ 4K HDR','32″ | 4K | HDR','10.990.000đ','','4.8 (55)','Mới')],bottom=['Giao nhanh 2H','Bảo hành chính hãng','Trả góp 0%','Đổi trả 30 ngày','Hệ thống 22 showroom'],cta='Màn hình chính hãng'),
10:dict(ch='06',topic='CONSOLE - SIM RACING - GIẢI TRÍ',title='GIẢI TRÍ<br><em>KHÔNG GIỚI HẠN</em>',desc='Thế giới game đỉnh cao.<br>Kết nối đam mê. Bùng nổ trải nghiệm.',accent='#e5b900',hero=(495,16,1260,395),brands=['PlayStation','Xbox','Nintendo','Steam Deck','Handheld','Sim Racing','VR','Game'],cats=['Tay cầm','Tai nghe Gaming','Đĩa game','Phụ kiện'],catbox=(1274,219,1994,309),call='Game hay hơn cùng phụ kiện chính hãng',calldesc='Tay cầm - Tai nghe - Dock sạc - Thẻ game - và hơn thế nữa',tabs=['Bán chạy','PlayStation','Xbox','Nintendo','Steam Deck','Handheld Gaming','Sim Racing','VR','Game','Phụ kiện'],geom=(43,245,471,556),items=[('Sony PlayStation 5 Slim','PS5 | 1TB SSD | 4K | Ray Tracing','14.990.000đ','','4.9 (256)','Bán chạy #1'),('Xbox Series X','1TB SSD | 4K | Game Pass','12.490.000đ','14.190.000đ','4.8 (128)','-12%'),('Nintendo Switch OLED','7 inch | 64GB | Joy-Con','8.990.000đ','','4.8 (96)','Mới về'),('Steam Deck OLED 1TB','7.4 inch | OLED | Steam OS','17.990.000đ','19.990.000đ','4.9 (78)','-10%'),('ROG Ally X','7 inch | Ryzen Z1 Extreme | 1TB','16.990.000đ','19.990.000đ','4.8 (64)','-15%'),('Logitech G923','Vô lăng | Pedal | TrueForce','9.990.000đ','','4.7 (112)','Hot'),('Meta Quest 3S','128GB | Reality Mixed','8.990.000đ','10.990.000đ','4.7 (90)','-18%'),('EA Sports FC 25 (PS)','Đĩa game PS5 | Bản quyền','1.590.000đ','1.990.000đ','4.8 (143)','-20%')],bottom=['Đĩa game mới nhất','Tay cầm chính hãng','Phụ kiện Console','Thẻ game & Gift Card','Ghế chơi game','Màn hình Gaming'],cta='Tư vấn chọn Console phù hợp'),
11:dict(ch='05',topic='GAMING GEAR',title='MỖI CÚ CLICK<br><em>ĐỀU QUAN TRỌNG</em>',desc='Trang bị gaming gear đỉnh cao.<br>Làm chủ mọi trận đấu.',accent='#19bc32',hero=(490,18,1200,395),brands=['Razer','Logitech','Corsair','SteelSeries','HyperX','Ducky'],cats=['Chuột Gaming','Bàn phím Cơ & Gaming','Tai nghe Gaming','Loa Vi tính','Ghế Gaming','Bàn Gaming','Streaming Setup','Phụ kiện Setup'],catbox=(1221,234,1996,307),call='Gear chuẩn game thủ - Nâng tầm trải nghiệm',calldesc='Từ chuột, bàn phím, tai nghe đến ghế gaming - Tất cả tại HACOM',tabs=['Bán chạy','Chuột','Bàn phím','Tai nghe','Loa','Ghế gaming','Bàn gaming','Streaming','Streaming','Setup desk','Mới về'],geom=(43,280,474,559),items=[('Razer DeathAdder V3 Pro','Wireless | 30K DPI | 63g','2.990.000đ','3.590.000đ','4.9 (256)','Bán chạy #1'),('Logitech G Pro X TKL','Mechanical | LIGHTSYNC RGB','3.690.000đ','4.490.000đ','4.8 (128)','-18%'),('SteelSeries Arctis Nova 5','Wireless | 100h | Multi-platform','4.990.000đ','','4.7 (96)','Mới về'),('Razer Leviathan V2 X','Soundbar | RGB | Bluetooth','2.690.000đ','3.499.000đ','4.8 (74)','-22%'),('Corsair T3 Rush','Gaming Chair | Ergonomic','5.990.000đ','','4.9 (56)','Hot'),('E-Dra EGT1460','Bàn Gaming | 140x60cm','2.990.000đ','3.490.000đ','4.7 (52)','-15%'),('Elgato Stream Deck MK.2','15 phím | LCD | Stream','4.990.000đ','','4.9 (48)','')],bottom=['Combo gear tiết kiệm','Gear cho game FPS','Gear cho game MOBA','Gear cho Streamer','Bộ setup hoàn chỉnh'],cta='Tư vấn chọn gear phù hợp'),
12:dict(ch='08',topic='MẠNG - LƯU TRỮ - PHẦN MỀM',title='KẾT NỐI<br><em>KHÔNG GIÁN ĐOẠN</em>',desc='Hạ tầng vững chắc.<br>Dữ liệu an toàn. Doanh nghiệp sẵn sàng tương lai.',accent='#009daf',hero=(490,18,1176,394),brands=['TP-Link','Synology','QNAP','ASUS','Cisco','Hikvision','Dahua','Western Digital'],cats=['Wifi','Network','NAS','Server','Lưu trữ','Cáp & Chuyển đổi','UPS','Phần mềm'],catbox=(1195,229,1997,302),call='Giải pháp hạ tầng mạng & lưu trữ toàn diện',calldesc='Kết nối nhanh hơn. Bảo mật cao hơn. Dữ liệu an toàn hơn.',tabs=['Bán chạy','Wifi','Network','NAS','Server','Lưu trữ','Cáp & Chuyển đổi','UPS','Phần mềm'],geom=(43,283,470,553),items=[('TP-Link Archer AX73','AX5400 | WiFi 6 | 4 Ăng ten | EasyMesh','2.490.000đ','3.290.000đ','4.8 (256)','Bán chạy #1'),('TP-Link Deco X50 (2 Pack)','AX3000 | Mesh WiFi 6 | Phủ sóng 420m²','3.990.000đ','4.890.000đ','4.7 (128)','-18%'),('Synology DS923+','4-Bay | AMD Ryzen | 4GB | Mở rộng','13.990.000đ','','4.9 (74)','Mới về'),('Cisco CBS250-24T-4G','24 Port | Gigabit | 4 SFP | Managed','8.490.000đ','9.990.000đ','4.8 (64)','-15%'),('WD My Passport 2TB','USB 3.2 | Portable HDD','2.290.000đ','','4.7 (112)','Hot'),('APC Back-UPS BX1600MI','1600VA | AVR | LCD | 4 Outlets','4.990.000đ','6.290.000đ','4.8 (90)','-20%'),('Windows 11 Pro','Bản quyền vĩnh viễn | 1 PC','4.990.000đ','','4.9 (156)','Bản quyền')],bottom=['Giải pháp WiFi toàn diện','Lưu trữ dữ liệu an toàn','Bảo mật mạng','Hỗ trợ triển khai tận nơi'],cta='Nhận tư vấn giải pháp miễn phí'),
13:dict(ch='09',topic='VĂN PHÒNG - DOANH NGHIỆP',title='GIẢI PHÁP<br><em>CHO DOANH NGHIỆP</em>',desc='Tối ưu hiệu suất làm việc.<br>Kiến tạo môi trường chuyên nghiệp.',accent='#006fed',hero=(562,18,1218,395),brands=['HP','Canon','EPSON','Brother','Logitech','ViewSonic','BenQ','Poly'],cats=['Máy in','Mực in','Scan & Photo','Máy chiếu','Hội nghị','POS','Chấm công','Văn phòng khác'],catbox=(1236,233,1995,297),call='Giải pháp văn phòng thông minh cho mọi quy mô',calldesc='Thiết bị chính hãng. Dịch vụ chuyên nghiệp. Đồng hành cùng doanh nghiệp Việt.',tabs=['Bán chạy','Máy in','Mực in','Máy & Photo','Scan & Photo','Máy chiếu','Hội nghị','POS','Chấm công','Văn phòng khác'],geom=(43,282,471,552),items=[('HP LaserJet Pro 4003dn','In đen trắng | 40 trang/phút | Duplex','6.990.000đ','8.990.000đ','4.8 (256)','Bán chạy #1'),('Canon LBP2900','In đen trắng | 12 trang/phút','2.990.000đ','3.690.000đ','4.7 (188)','-18%'),('Epson L3250','In - Scan - Copy | WiFi | In màu','4.690.000đ','','4.8 (312)','Mới về'),('ViewSonic PA503S','3800 ANSI | SVGA | HDMI','7.990.000đ','9.490.000đ','4.7 (96)','-15%'),('Logitech Rally Bar Mini','4K | AI Framing | Họp trực tuyến','64.990.000đ','','4.9 (48)','Hot'),('Ronald Jack RJ550A','Chấm công vân tay | WiFi','2.790.000đ','3.490.000đ','4.6 (124)','-20%'),('Fellowes 99Ci','Máy hủy tài liệu | 17 tờ | Cross-cut','8.990.000đ','','4.8 (72)','Dự án')],bottom=['Báo giá dự án','Lắp đặt tận nơi','Bảo hành chuyên nghiệp','Ưu đãi doanh nghiệp','Ưu đơn doanh đâyđo','Hóa đơn VAT đầy đủ'],cta='Liên hệ tư vấn doanh nghiệp'),
14:dict(ch='10',topic='SMART HOME - CAMERA - GIA DỤNG',title='NHÀ THÔNG MINH<br><em>CUỘC SỐNG TIỆN NGHI</em><br>AN TOÀN HƠN MỖI NGÀY',desc='Sản phẩm chính hãng, đa dạng thương hiệu.<br>Giải pháp thông minh cho mọi gia đình.<br>Dễ dàng lắp đặt, sử dụng.<br>Bảo vệ an toàn - Nâng tầm cuộc sống.',accent='#ff7000',hero=(538,0,1270,380),brands=[],cats=['An ninh toàn diện','Nhà thông minh','Chiếu sáng thông minh','Gia dụng thông minh','Chăm sóc sức khỏe','Cho gia đình có trẻ nhỏ','Cho văn phòng - cửa hàng','Du lịch và di chuyển'],catbox=None,call='GIẢI PHÁP NHÀ THÔNG MINH TOÀN DIỆN',calldesc='An toàn · Tiện nghi · Tiết kiệm · Hiện đại',tabs=['Camera','Khóa Thông Minh','Báo Cháy','Nhà Thông Minh','Điện Thông Minh','Gia Dụng','Sức Khỏe','Camera Hành Trình & Drone'],geom=(88,320,447,542),items=[('Camera EZVIZ H6c 2K+','Camera trong nhà xoay 360°','690.000đ','920.000đ','4.8 (256)','-25%'),('Camera IMOU Ranger 2C','Camera AI trong nhà','790.000đ','990.000đ','4.7 (182)','-20%'),('Camera TP-Link Tapo C320WS','Camera ngoài trời, màu ban đêm','1.090.000đ','1.329.000đ','4.8 (174)','-18%'),('Camera Xiaomi Outdoor AW300','Camera ngoài trời, WiFi 6','1.490.000đ','1.890.000đ','4.7 (98)','-22%'),('Camera Hikvision DS-2CD2423G2-I','Camera AI, có màu ban đêm','1.990.000đ','2.790.000đ','4.8 (112)','-28%'),('Camera EZVIZ EB8 4G','Camera 4G, pin năng lượng mặt trời','2.490.000đ','2.950.000đ','4.9 (76)','-15%')],bottom=['Giao nhanh 2H','Hàng chính hãng 100%','Lắp đặt tận nơi','Tư vấn giải pháp miễn phí','Ưu đãi thành viên','Bảo hành & hỗ trợ kỹ thuật'],cta='Xem tất cả giải pháp'),
15:dict(ch='10',topic='DỊCH VỤ - LẮP RÁP - NÂNG CẤP PC',title='DỊCH VỤ PC<br><em>TRỌN GÓI TẠI HACOM</em>',desc='Tư vấn tận tâm. Lắp ráp chuyên nghiệp.<br>Hiệu năng tối ưu. Đồng hành lâu dài.',accent='#ed0028',hero=(575,18,1168,414),light=True,brands=[],cats=['Lắp ráp PC theo yêu cầu','Nâng cấp PC','Vệ sinh PC','Cài đặt phần mềm','Bảo trì - Kiểm tra lỗi','Tư vấn doanh nghiệp','Thu cũ đổi mới','Bảo hành & hỗ trợ'],catbox=None,call='Dịch vụ kỹ thuật HACOM',calldesc='Nhanh chóng - Chuyên nghiệp - Tin cậy',tabs=['PC Gaming','PC Đồ họa','PC Văn phòng','PC AI/Workstation','Build theo ngân sách','Combo khuyến mãi'],geom=(42,330,495,614),horizontal=True,items=[('HACOM Gaming EZ','Core i5 | RTX 4060 | 16GB','18.990.000đ','','',''),('HACOM Gaming Plus','Ryzen 5 | RTX 5060 | 16GB','24.990.000đ','','',''),('HACOM Ultimate','Core i7 | RTX 5070 | 32GB','39.990.000đ','','',''),('HACOM Pro Creator','Ryzen 7 | RTX 5070 | 32GB','42.990.000đ','','',''),('HACOM AI Workstation','Core i9 | RTX 5080 | 64GB','89.990.000đ','','',''),('HACOM Office','Core i5 | UHD | 16GB','12.990.000đ','','','')],bottom=['Giao hàng toàn quốc','Bảo hành chính hãng','Hỗ trợ kỹ thuật trọn đời','Tư vấn 1:1 miễn phí'],cta='Tư vấn cấu hình ngay'),
16:dict(ch='11',topic='PHỤ KIỆN - THIẾT BỊ NGOẠI VI',title='PHỤ KIỆN CHÍNH HÃNG<br><em>TRỌN TRẢI NGHIỆM</em>',desc='Đa dạng phụ kiện, nâng tầm hiệu suất.<br>Chơi game, làm việc, học tập tốt hơn mỗi ngày.',accent='#ef002b',hero=(570,18,1159,395),brands=['Logitech','Razer','Corsair','HyperX','SteelSeries','ASUS','UGREEN','Baseus'],cats=['Tai nghe','Bàn phím','Chuột','Lót chuột','Webcam','Micro','Cáp & Chuyển đổi','Túi & Balo','Đế tản nhiệt','Phụ kiện khác'],catbox=(1186,234,1998,302),call='Phụ kiện chính hãng - Đa dạng lựa chọn',calldesc='Từ gaming gear đến phụ kiện văn phòng. Tất cả tại HACOM!',tabs=['Sản phẩm nổi bật','Tai nghe','Bàn phím','Chuột','Chuột','Lót chuột','Webcam','Micro','Cáp & Chuyển đổi','Túi & Balo','Phụ kiện khác'],geom=(43,282,471,553),items=[('Logitech G733 Lightspeed','Wireless | RGB | 29h pin','2.990.000đ','','4.8 (256)','Bán chạy #1'),('Razer BlackWidow V4 X','Mechanical | Green Switch | RGB','3.690.000đ','4.490.000đ','4.8 (128)','-18%'),('Logitech G Pro X Superlight 2','Wireless | 60g | HERO 2','2.990.000đ','','4.9 (96)','Mới về'),('SteelSeries QcK Heavy','Gaming Mousepad | Size L','490.000đ','630.000đ','4.7 (74)','-22%'),('Logitech C922 Pro','Full HD 1080p | 60fps','2.290.000đ','','4.8 (112)','Hot'),('HyperX QuadCast S','USB | RGB | Anti-Vibration','3.990.000đ','4.690.000đ','4.8 (90)','-15%'),('Razer Rogue Backpack V3','Chống nước | 17 inch','1.590.000đ','1.990.000đ','4.7 (64)','-20%')],bottom=['Giao hàng nhanh 2H','Sản phẩm chính hãng','Hỗ trợ tư vấn tận tâm','Ưu đãi thành viên'],cta='Khám phá thêm nhiều phụ kiện'),
17:dict(ch='14',topic='BẢO HÀNH - HẬU MÃI - DỊCH VỤ',title='DỊCH VỤ HẬU MÃI<br><em>AN TÂM DÀI LÂU</em>',desc='Đồng hành cùng bạn trong suốt quá trình sử dụng.<br>Nhanh chóng - Minh bạch - Chuyên nghiệp.',accent='#ed0028',hero=(552,18,1170,399),light=True,brands=[],cats=['Bảo hành chính hãng','Hỗ trợ kỹ thuật chuyên sâu','Sửa chữa nhanh lấy liền','Nâng cấp phần cứng & vệ sinh máy','Thu cũ đổi mới tiết kiệm chi phí','Cài đặt phần mềm & tối ưu hệ thống','Sao lưu & khôi phục dữ liệu','Gia hạn bảo hành mở rộng','Hệ thống 22 showroom toàn quốc','Tư vấn & hỗ trợ sau bán hàng'],catbox=None,call='Trung tâm bảo hành & hỗ trợ kỹ thuật HACOM',calldesc='Luôn sẵn sàng phục vụ bạn trên toàn quốc',tabs=['Dịch vụ nổi bật','Bảo hành','Sửa chữa','Nâng cấp','Vệ sinh PC/Laptop','Cài đặt phần mềm','Thu cũ đổi mới'],geom=(43,282,476,561),items=[('Vệ sinh laptop cơ bản','Làm sạch - Tra keo tản nhiệt','150.000đ','','',''),('Vệ sinh PC chuyên sâu','Làm sạch - Tra keo cao cấp','250.000đ','','',''),('Nâng cấp SSD','Tư vấn & lắp đặt tận nơi','Từ 100.000đ','','',''),('Nâng cấp RAM','Tư vấn & lắp đặt tận nơi','Từ 50.000đ','','',''),('Cài đặt Windows','Bản quyền - Tối ưu hệ thống','150.000đ','','',''),('Cài đặt phần mềm','Văn phòng - Đồ họa - Game','Từ 100.000đ','','',''),('Thu cũ đổi mới','Định giá nhanh - Thủ tục đơn giản','Liên hệ','','','')],bottom=['Hỗ trợ toàn quốc','Quy trình minh bạch','Đội ngũ kỹ thuật viên chuyên nghiệp','Xử lý nhanh chóng'],cta='Cần hỗ trợ ngay?'),
18:dict(ch='15',topic='SỐNG XANH - THU CŨ ĐỔI MỚI',title='THU CŨ ĐỔI MỚI<br><em>SỐNG XANH CÙNG HACOM</em>',desc='Lên đời thiết bị dễ dàng. Bảo vệ môi trường hôm nay.<br>Vì một tương lai bền vững.',accent='#00852e',hero=(615,18,1218,412),light=True,brands=[],cats=[],catbox=None,call='QUY TRÌNH THU CŨ ĐỔI MỚI',calldesc='Chỉ 4 bước đơn giản, lên đời thiết bị dễ dàng',tabs=['Laptop','PC - Linh kiện','Màn hình','Điện thoại - Tablet','Thiết bị văn phòng'],geom=(43,330,488,572),trade=True,items=[('MacBook Air M2 13 inch','Thu cũ lên đời - Giá tốt','Từ 18.990.000đ','','','Trợ giá đến 5.000.000đ'),('Dell XPS 13','Thu cũ lên đời - Giá tốt','Từ 16.990.000đ','','','Trợ giá đến 3.000.000đ'),('ASUS ROG Zephyrus G14','Thu cũ lên đời - Giá tốt','Từ 24.990.000đ','','','Trợ giá đến 4.000.000đ'),('Lenovo ThinkPad X1','Thu cũ lên đời - Giá tốt','Từ 14.990.000đ','','','Trợ giá đến 2.000.000đ'),('HP Victus 16','Thu cũ lên đời - Giá tốt','Từ 17.990.000đ','','','Trợ giá đến 3.000.000đ'),('Acer Nitro V 15','Thu cũ lên đời - Giá tốt','Từ 15.990.000đ','','','Trợ giá đến 2.000.000đ')],bottom=['Góp phần bảo vệ môi trường','Thiết bị được tái sử dụng an toàn','Dữ liệu được xóa sạch','Hỗ trợ thu tận nơi'],cta='Hành động xanh cùng HACOM')
}

def servicegrid(names):
    icons=['desktop','gear','fan','display','shield-halved','building','coins','headset','cube','screwdriver-wrench']
    return '<div class="hs-service-grid">'+''.join(a(ic(icons[i%len(icons)])+f'<strong>{name}</strong>'+ic('arrow-right')) for i,name in enumerate(names))+'</div>'
HERO_BENEFITS={
5:['Hiệu năng vượt trội','Thiết kế mỏng nhẹ','Pin lâu dài','Pin lâu dài hơn','AI hỗ trợ công việc'],
6:['Hiệu năng vượt trội','Lắp ráp theo yêu cầu','Bảo hành chính hãng','Hỗ trợ trọn đời'],
8:['Hàng chính hãng 100%','Đa dạng thương hiệu','Hiệu suất vượt trội','Tối ưu nâng cấp'],
9:['Hình ảnh sắc nét','Tần số quét vượt trội','Công nghệ hiển thị tiên tiến','Đa dạng nhu cầu sử dụng'],
10:['Game chính hãng 100%','Giao nhanh 2H - 24H','Bảo hành chính hãng','Cộng đồng Game thủ'],
11:['Hiệu suất vượt trội','Thiết kế đậm chất game','Đa dạng thương hiệu','Bảo hành chính hãng'],
12:['Tốc độ vượt trội','Bảo mật toàn diện','Lưu trữ linh hoạt','Giải pháp cho mọi quy mô'],
13:['Đa dạng sản phẩm','Giải pháp toàn diện','Hỗ trợ dự án & doanh nghiệp','Tư vấn chuyên sâu'],
14:[],
15:['Đội ngũ chuyên gia','Lắp ráp chuẩn kỹ thuật','Tối ưu hiệu năng theo nhu cầu','Hỗ trợ sau bán hàng'],
16:['Chính hãng 100%','Giao hàng nhanh 2H','Đa dạng thương hiệu','Hỗ trợ tư vấn tận tâm'],
17:['Bảo hành chính hãng','Hỗ trợ kỹ thuật chuyên sâu','Xử lý nhanh trong 24h','Tư vấn tận tâm trọn vòng đời'],
18:['Định giá nhanh chóng','Quy trình minh bạch','Thu cũ tận nơi toàn quốc','Ưu đãi hấp dẫn khi lên đời']}
for n,d in CHAPTERS.items():
    art=crop(n,'hero-artwork',d['hero'])
    hero=f'<div class="hs-chapter-hero {"is-light" if d.get("light") else ""}">'+img(art,d['topic'],'hs-chapter-art')+f'<div class="hs-chapter-copy"><p class="hs-chapter-label">CHAPTER {d["ch"]} / {d["topic"]}</p><h1 id="s{n}-title" data-section-heading>{d["title"]}</h1><p class="hs-chapter-description">{d["desc"]}</p>'+(benefits(HERO_BENEFITS[n]) if HERO_BENEFITS[n] else '')+a(('Định giá thiết bị ngay' if n==18 else 'Khám phá dịch vụ' if n==17 else 'Khám phá ngay')+' '+ic('arrow-right'),'hs-cta')+'</div></div>'
    side=brandrow(d['brands']) if d['brands'] else ''
    side+=callout(d['call'],d['calldesc'],{12:'Xem ngay',13:'Nhận tư vấn',15:'Xem tất cả dịch vụ',16:'Xem ngay',17:'Tìm trung tâm gần nhất',18:'Xem hướng dẫn chi tiết',10:'Xem ngay',11:'Xem ngay'}.get(n,'Khám phá ngay'))
    if d['catbox']:
        side+=category_tiles(n,d['cats'],d['catbox'],len(d['cats']))
    elif d['cats']:side+=servicegrid(d['cats'])
    if n==14:
        subtitles=['Camera - Khóa - Báo cháy','Điều khiển mọi thiết bị','Tiết kiệm - Linh hoạt','Nhẹ nhàng cuộc sống','Thư giãn mỗi ngày','An toàn và tiện nghi','Giám sát & bảo vệ','Camera hành trình - Drone']
        side=callout(d['call'],d['calldesc'],'Xem tất cả giải pháp')+'<div class="hs-solutions-grid">'
        for i,name in enumerate(d['cats']):
            row,col=divmod(i,4);x=1280+col*181;y=77+row*139
            side+=a(img(crop(n,f'solution-{i+1}',(x+20,y,x+158,y+72)),name)+f'<strong>{name}</strong><small>{subtitles[i]}</small>')
        side+='</div>'
    if n==10:
        platforms='<div class="hs-brands hs-platforms" tabindex="0" aria-label="Nền tảng chơi game">'
        for i,name in enumerate(d['brands']):
            x=1278+i*91
            platforms+=a(img(crop(n,f'platform-{i+1}',(x+25,40,x+66,76)),name)+f'<span>{name}</span>','is-selected' if i==0 else '')
        side=platforms+'</div>'+callout(d['call'],d['calldesc'],'Xem ngay')+category_tiles(n,d['cats'],d['catbox'],4)
    if n==8:side+=benefits(['Tư vấn cấu hình miễn phí','Dịch vụ Build PC chuyên nghiệp','Giao nhanh toàn quốc'])
    if n==9:side+='<div class="hs-oled">'+img(crop(n,'oled',(1610,94,1800,339)),'Màn hình OLED')+'<div><h3>ĐỈNH CAO TRẢI NGHIỆM</h3><p>Màu sắc chân thực<br>Tương phản vô hạn<br>Lựa chọn của game thủ</p>'+a('Khám phá ngay '+ic('arrow-right'),'hs-cta')+'</div></div>'
    if n==18:
        side+='<ol class="hs-process">'+''.join(f'<li><b>{i+1}</b>'+ic(g)+f'<strong>{t}</strong><p>{desc}</p></li>' for i,(g,t,desc) in enumerate([('magnifying-glass','Định giá online','Nhập thông tin thiết bị của bạn'),('truck-fast','Kiểm tra & thu máy','Kỹ thuật viên HACOM xác nhận và thu máy'),('gear','Nhận ưu đãi','Nhận ngay voucher hấp dẫn'),('laptop','Lên đời thiết bị mới','Tận hưởng công nghệ mới, hiệu suất cao hơn')]))+'</ol>'+callout('Cùng HACOM giảm rác thải công nghệ','Mỗi thiết bị được tái sử dụng là một bước tiến cho môi trường xanh hơn.','Tìm hiểu thêm')
    if n==9:
        side=filters(['Màn Hình Gaming','Màn Hình Văn Phòng','Màn Hình Đồ Họa','Theo Hãng','TV','Phụ Kiện'],'')+'<div class="hs-monitor-discovery"><div class="hs-monitor-brands">'
        for i,(name,box) in enumerate([('ASUS ROG',(1060,116,1149,170)),('ASUS TUF',(1202,113,1270,178)),('LG Gaming',(1328,119,1432,175)),('Dell Gaming',(1479,115,1552,181)),('MSI',(1060,260,1148,301)),('',(1220,260,1290,301)),('MSI',(1380,260,1439,302)),('GIGABYTE',(1452,260,1570,305))]):
            side+=a(img(crop(n,f'monitor-brand-{i+1}',box),name)+f'<span>{name}</span>') if name else '<span aria-hidden="true"></span>'
        side+='</div><div class="hs-oled">'+img('assets/images/sections/s9-oled.webp','Màn hình OLED')+'<div><h3>MÀN HÌNH OLED</h3><strong>ĐỈNH CAO TRẢI NGHIỆM</strong><p>Màu sắc chân thực<br>Tương phản vô hạn<br>Lựa chọn của game thủ</p>'+a('Khám phá ngay '+ic('arrow-right'),'hs-cta')+'</div></div></div>'
    body='<div class="hs-chapter-top">'+hero+'<div class="hs-chapter-side">'+side+'</div></div>'+filters(d['tabs'])+productrail(n,d['items'],d['geom'],d.get('trade',False),d.get('horizontal',False),n not in [15,17,18])+strip(d['bottom'],d['cta'])
    write(n,body,d['accent'],'hs-chapter'+(' hs-monitor' if n==9 else ''))

# Section 2 — five main category cards and six secondary tiles.
big=[('LAPTOP',['Laptop Văn Phòng','Laptop Gaming','Laptop AI','MacBook','Surface','Laptop Đồ Họa'],(43,265,343,422),'#0769ff'),('PC & ALL IN ONE',['PC Văn Phòng','PC Gaming','PC Đồ Họa – Workstation','All In One','Mini PC'],(389,262,677,424),'#e90022'),('LINH KIỆN PC',['CPU','Mainboard','RAM','Ổ cứng','Tản nhiệt'],(730,260,1047,466),'#005eff'),('MÀN HÌNH & TV',['Màn hình','TV','Giá treo','Phụ kiện'],(1110,266,1373,432),'#f59916'),('GAMING GEAR',['Bàn phím','Chuột','Tai nghe','Ghế gaming','Phụ kiện'],(1438,253,1715,434),'#ef123b')]
body=heading(2,'BƯỚC VÀO THẾ GIỚI CÔNG NGHỆ','Đa dạng lựa chọn · Sản phẩm chính hãng · Luôn cập nhật xu hướng mới nhất','KHÁM PHÁ DANH MỤC NỔI BẬT')+'<div class="hs-maincategories">'
for i,(name,links,box,color) in enumerate(big):
    body+=f'<article class="hs-maincategory {"is-featured" if i==2 else ""}" style="--card-accent:{color}"><span class="hs-category-number">0{i+1}</span>'+('<span class="hs-ai-label">AI READY</span>' if i==2 else '')+f'<h3>{name}</h3>'+img(crop(2,f'large-category-{i+1}',box),name)+('<div class="hs-componentlinks">'+ ' | '.join(a(t) for t in links)+'</div>' if i==2 else '<ul>'+''.join('<li>'+a(t+' '+ic('chevron-right'))+'</li>' for t in links)+'</ul>')+'</article>'
body+='</div><div class="hs-smallcategories">'
small=['CONSOLE & SIM RACING','ÂM THANH & STREAM','MẠNG & LƯU TRỮ','VĂN PHÒNG & DOANH NGHIỆP','SMART HOME & GIA DỤNG','HÀNG MỚI & KHUYẾN MÃI']
for i,t in enumerate(small):
    body+=a(f'<span><small>{i+6:02}</small><strong>{t}</strong></span>'+img(crop(2,f'small-category-{i+1}',(140+i*288,654,243+i*288,747)),t)+ic('arrow-right'))
body+='</div>'+strip(['THƯƠNG HIỆU CHÍNH HÃNG','GIÁ TỐT MỖI NGÀY','NHIỀU QUÀ TẶNG HẤP DẪN'],'Khám phá tất cả danh mục')
write(2,body,'#066aff','hs-discovery')

# Section 3 — professions. Only portraits are raster artwork.
professions=[('Sinh viên','#006bff',['Học tập hiệu quả','Lập trình, làm đồ án','Sẵn sàng cho tương lai'],['Laptop','Tablet','Phụ kiện']),('Game thủ','#ff0037',['Hiệu năng đỉnh cao','Chiến mọi tựa game','Trải nghiệm mượt mà'],['Gaming Laptop','Gaming PC','Gaming Gear']),('Dân văn phòng','#00b88e',['Làm việc hiệu quả','Di chuyển linh hoạt','Cân bằng cuộc sống'],['Laptop','PC để bàn','Màn hình']),('Designer','#ff8000',['Thiết kế 2D/3D chuyên nghiệp','Màu sắc chuẩn xác','Sáng tạo không giới hạn'],['Laptop đồ họa','Màn hình đồ họa','Bảng vẽ']),('Video Editor','#a600ff',['Dựng phim mượt mà','Xử lý video 4K/8K','Hiệu ứng chuyên nghiệp'],['Workstation','Màn hình 4K','Lưu trữ']),('Kiến trúc sư','#c7a100',['Thiết kế không giới hạn','Render nhanh, mượt','Kiến tạo không gian sống'],['Workstation','Màn hình lớn','Phần mềm']),('AI User','#009bff',['Sức mạnh AI, Machine Learning','Xử lý dữ liệu lớn','Dẫn đầu xu hướng'],['AI Laptop','AI PC','GPU & Linh kiện']),('Streamer','#ed0079',['Livestream mượt mà','Thu hút mọi ánh nhìn','Sáng tạo nội dung chuyên nghiệp'],['Streaming PC','Webcam','Micro'])]
body=heading(3,'Chọn đúng máy <em>theo nghề nghiệp</em>','Mỗi công việc đều có giải pháp công nghệ phù hợp. Khám phá ngay cùng HACOM!')+'<div class="hs-professions" tabindex="0" aria-label="Giải pháp theo nghề nghiệp">'
for i,(name,color,perks,suggestions) in enumerate(professions):
    art=crop(3,f'profession-{i+1}',(18+i*267,158,277+i*267,336))
    body+=f'<article class="hs-profession" style="--card-accent:{color}">'+img(art,name)+f'<div><h3>{name}</h3><ul>'+''.join('<li>'+ic('circle-check')+' '+t+'</li>' for t in perks)+'</ul><strong class="hs-suggest-label">Sản phẩm gợi ý</strong><div class="hs-suggestions">'+''.join(a(ic(['laptop','display','headset'][j])+f'<span>{t}</span>') for j,t in enumerate(suggestions))+'</div>'+a('Khám phá ngay '+ic('arrow-right'),'hs-profession-cta')+'</div></article>'
body+='</div><div class="hs-pagination" aria-label="Trang đầu trong sáu trang"><span class="is-selected"></span>'+ '<span></span>'*5+'</div>'+a('Khám phá thêm giải pháp tại HACOM '+ic('arrow-right'),'hs-more')
write(3,body,'#ed0028','hs-careers')

# Section 4 — Deal Center.
deals=[('ASUS ROG Strix G16 2024','i7-13650HX | 16GB | 1TB SSD | RTX 4060','32.990.000đ','48.990.000đ','4.8 (128)','-32%'),('Lenovo Legion Pro 5','Ryzen 7 7745HX | 16GB | 1TB | RTX 4060','29.990.000đ','41.990.000đ','4.7 (96)','-28%'),('Gigabyte RTX 5080 Gaming OC','16GB GDDR7 | DLSS 4 | AI Ready','28.990.000đ','38.990.000đ','4.9 (56)','-25%'),('LG UltraGear 27″ OLED','2K | 240Hz | 0.03ms | HDR True Black','18.990.000đ','23.990.000đ','4.8 (74)','-20%'),('Logitech G Pro X 2','Wireless | Blue VO!CE | 50mm','4.590.000đ','6.990.000đ','4.9 (112)','-34%')]
body='<div class="hs-deal-top"><div class="hs-deal-intro"><p class="hs-eyebrow">HACOM / DEAL CENTER</p><h1 id="s4-title" data-section-heading>DEAL<br><em>CENTER</em></h1><h3>SĂN DEAL CỰC HOT<br>NÂNG TẦM TRẢI NGHIỆM</h3>'+benefits(['Số lượng có hạn','Cam kết chính hãng','Giá tốt nhất thị trường'])+'</div><div class="hs-deal-main"><div class="hs-deal-tabs">'+''.join(a(f'<strong>{t}</strong><span>{s}</span>','is-selected' if i==0 else '') for i,(t,s) in enumerate([('⚡ Flash Sale','Giờ vàng - Giá sốc mỗi ngày'),('🔥 Hot Trend','Xu hướng công nghệ mới nhất'),('New Arrival','Hàng mới về - Trải nghiệm sớm')]))+'<div class="hs-countdown"><span>Kết thúc sau</span><strong>04 : 32 : 18</strong><small>Giờ　 Phút　 Giây</small></div></div>'+productrail(4,deals,(453,251,156,291))+'</div><div class="hs-deal-art">'+img(crop(4,'deal-robot',(1725,121,2042,449)),'Robot HACOM cầm bảng Tech Better Life')+a('Xem tất cả deal '+ic('arrow-right'),'hs-cta')+'</div></div><div class="hs-deal-explore">'
for i,(title,desc,box,tiles) in enumerate([('FLASH SALE<br>THEO DANH MỤC','Săn deal nhanh theo nhu cầu của bạn',(318,483,672,642),['Laptop','PC Gaming','VGA','Màn hình','Gaming Gear']),('HOT TREND<br>CÔNG NGHỆ 2025','Những xu hướng dẫn đầu đã có tại HACOM',(957,483,1322,642),['AI PC','RTX 50 Series','OLED Monitor','Laptop AI','Handheld Gaming']),('NEW ARRIVAL<br>HÀNG MỚI VỀ','Cập nhật sản phẩm mới nhất từ các thương hiệu hàng đầu',(1609,483,2002,642),['Hàng mới nhập','Hàng vừa ra mắt','Pre-order','Độc quyền tại HACOM','Sản phẩm nổi bật'])]):
    body+='<article><div class="hs-explore-banner"><h3>'+title+'</h3><p>'+desc+'</p>'+img(crop(4,f'explore-{i+1}',box),'')+a(ic('arrow-right'),'hs-round-link')+'</div><div class="hs-explore-tiles">'+''.join(a(ic(['laptop','desktop','microchip','display','headset'][j])+'<span>'+t+'</span>') for j,t in enumerate(tiles))+'</div></article>'
body+='</div>';write(4,body,'#f0002b','hs-deals')

# Section 19 — all numbers are real text.
numbers=[('25+','NĂM KINH NGHIỆM','Đồng hành cùng người Việt<br>từ năm 2001'),('20+','SHOWROOM','Trải dài từ Bắc vào Nam'),('1.000.000+','KHÁCH HÀNG','Tin tưởng lựa chọn HACOM'),('500+','THƯƠNG HIỆU','Đối tác công nghệ toàn cầu'),('50.000+','SẢN PHẨM','Từ Laptop tới AI Workstation'),('100+','CHUYÊN GIA','Tư vấn giải pháp công nghệ'),('24/7','HỖ TRỢ','Đồng hành cùng khách hàng'),('10.000+','ĐƠN HÀNG / THÁNG','Hệ thống vận hành toàn quốc')]
body=heading(19,'<em>HACOM</em> IN NUMBERS','<strong>Những con số tạo nên niềm tin</strong><br>Hơn 20 năm đồng hành cùng người Việt, HACOM không ngừng kiến tạo giá trị,<br>mang công nghệ đến gần hơn với mọi người.','HACOM')+'<div class="hs-numbers">'+''.join('<article><strong>'+v+'</strong><h3>'+t+'</h3><p>'+d+'</p></article>' for v,t,d in numbers)+'</div><p class="hs-tagline">TECH FOR A BETTER TOMORROW</p>'
write(19,body,'#ed001e','hs-number-section')

# Section 20 — news, article search and newsletter, no submitting forms.
featured=[('Top 5 laptop AI đáng mua nhất 2026 cho học tập và làm việc','10/09/2026','12.5K',(1184,32,1351,140)),('RTX 50 Series: Bước nhảy hiệu năng cho game thủ và nhà sáng tạo nội dung','08/09/2026','9.8K',(1184,169,1351,263)),('Hướng dẫn build PC gaming 2026: Cấu hình, linh kiện và chi phí','05/09/2026','15.2K',(1184,290,1351,383))]
articles=[('MacBook M4 2026: Có gì mới và có đáng nâng cấp?','10/09/2026','8.4K',(49,478,319,572)),('Đánh giá ASUS ROG Zephyrus G16 2026: Mỏng nhẹ nhưng mạnh mẽ','09/09/2026','6.1K',(356,478,625,572)),('Hướng dẫn chọn nguồn PC phù hợp cho từng cấu hình','07/09/2026','5.7K',(663,478,932,572)),('Top 7 màn hình 2K 240Hz tốt nhất cho game thủ 2026','05/09/2026','10.3K',(967,478,1237,572)),('Gear gaming 2026: Những món phụ kiện đáng đầu tư nhất','03/09/2026','4.9K',(1275,478,1546,572))]
newshero='<div class="hs-chapter-hero">'+img(crop(20,'hero-artwork',(575,19,1160,397)),'Chuyên gia HACOM tìm hiểu công nghệ','hs-chapter-art')+'<div class="hs-chapter-copy"><p class="hs-chapter-label">CHAPTER 16 / KIẾN THỨC - TIN TỨC - TƯ VẤN</p><h1 id="s20-title" data-section-heading>KIẾN THỨC CÔNG NGHỆ<br><em>KẾT NỐI ĐAM MÊ</em></h1><p>Cập nhật tin tức, đánh giá, hướng dẫn và xu hướng công nghệ mới nhất từ HACOM.</p>'+a('Khám phá ngay '+ic('arrow-right'),'hs-cta')+benefits(['Tin tức công nghệ','Hướng dẫn sử dụng','Đánh giá sản phẩm','Tư vấn chuyên sâu'])+'</div></div>'
body='<div class="hs-news-top">'+newshero+'<div class="hs-featured-news">'
for i,(title,date,views,box) in enumerate(featured):body+=a(img(crop(20,f'featured-{i+1}',box),title)+f'<div><h3>{title}</h3><p>{date}<span>{ic("eye")} {views}</span></p></div>')
hot=['So sánh RTX 5060 vs 5070: Nên chọn card đồ họa nào?','Top màn hình OLED 2026 cho game thủ','Hướng dẫn cài Windows 11 chi tiết từ A-Z','Laptop cho sinh viên 2026: Nên chọn hãng nào?','Cách vệ sinh laptop đúng cách tại nhà']
body+='</div><aside class="hs-hot-news"><h3>'+ic('fire')+' Bài viết <em>HOT</em></h3><ol>'+''.join(f'<li><b>{i+1}</b>'+a(t)+'</li>' for i,t in enumerate(hot))+'</ol>'+a('Xem tất cả '+ic('arrow-right'))+'</aside></div>'+filters(['Tất cả','Laptop','PC Gaming','Linh kiện','Màn hình','Gaming Gear','Phụ kiện','Thủ thuật','Xu hướng'],'Chủ đề nổi bật')+'<div class="hs-news-bottom"><div class="hs-articles">'
for i,(title,date,views,box) in enumerate(articles):body+='<article>'+a(img(crop(20,f'article-{i+1}',box),title)+f'<h3>{title}</h3>')+f'<p>{date}<span>{ic("eye")} {views}</span></p></article>'
body+='</div><aside class="hs-news-signup"><div class="hs-inputrow"><label for="s20-search" class="sr-only">Tìm kiếm bài viết</label><input id="s20-search" type="search" placeholder="Tìm kiếm bài viết...">'+btn('Tìm kiếm',cls='hs-cta')+'</div><div class="hs-newsletter"><h3>'+ic('envelope')+' Đăng ký nhận tin công nghệ</h3><p>Cập nhật xu hướng, khuyến mãi và bài viết mới nhất từ HACOM.</p><div class="hs-inputrow"><label for="s20-email" class="sr-only">Email nhận tin công nghệ</label><input id="s20-email" type="email" placeholder="Nhập email của bạn...">'+btn('Đăng ký',cls='hs-cta')+'</div><label class="hs-checkbox"><input type="checkbox" checked> Tôi đồng ý nhận thông tin từ HACOM</label></div></aside></div>'+strip(['Nội dung chính xác','Đội ngũ giàu kinh nghiệm','Cập nhật liên tục','Kiến thức thực tiễn'],'Xem tất cả bài viết')
write(20,body,'#ed0028','hs-news')

# Section 21 — seven static thumbnails and metadata, play controls are HTML.
videos=[('Unbox ASUS ROG Zephyrus G16 2026 – Laptop gaming mỏng nhẹ, hiệu năng đỉnh cao','12:45','125K lượt xem · 3 ngày trước',(46,122,803,554)),('Unbox & test RTX 5070 – Sức mạnh đồ họa thế hệ mới','10:32','98K lượt xem · 5 ngày trước',(828,123,1197,294)),('Review LG OLED 32″ 4K – Màn hình cho trải nghiệm hình ảnh hoàn hảo','8:21','76K lượt xem · 1 tuần trước',(1218,123,1604,294)),('Hướng dẫn build PC Gaming 2026 – Cấu hình mạnh mẽ, tối ưu chi phí','14:18','63K lượt xem · 1 tuần trước',(1625,123,1998,294)),('Review MacBook M4 2026 – Những nâng cấp đáng giá','9:15','52K lượt xem · 2 tuần trước',(828,395,1197,565)),('Unbox AKKO 3108 RF V3 – Thiết kế độc đáo, trải nghiệm khác biệt','6:40','41K lượt xem · 2 tuần trước',(1218,395,1604,565)),('Review ghế công thái học – Giải pháp cho dân văn phòng','7:28','36K lượt xem · 2 tuần trước',(1625,395,1998,565))]
body='<div class="hs-video-header">'+heading(21,'VIDEO <em>UNBOX & REVIEW</em>','Khám phá sản phẩm thực tế, đánh giá khách quan từ đội ngũ HACOM')+filters(['Tất cả','Laptop','PC & Linh kiện','Màn hình','Gaming Gear','Thiết bị văn phòng'],'Xem tất cả video')+'</div><div class="hs-videos">'
for i,(title,duration,meta,box) in enumerate(videos):
    # Use clean central product/photo crop, recreate thumbnail titles and play overlay.
    x1,y1,x2,y2=box
    if i==0: clean=(x1+290,y1+70,x2-50,y2-45)
    elif i in [1,2,3,4,5,6]:clean=(x1+(80 if i!=5 else 20),y1+55,x2-25,y2-24)
    videoassets=['assets/images/section-1/laptop-artwork.webp','assets/images/sections/s8-product-3.webp','assets/images/sections/s9-product-7.webp','assets/images/sections/s6-product-1.webp','assets/images/sections/s5-product-6.webp','assets/images/sections/s11-product-2.webp','assets/images/sections/s11-product-5.webp']
    body+=f'<article class="hs-video {"is-featured" if i==0 else ""}"><div class="hs-video-thumb">'+img(videoassets[i],title)+f'<span class="hs-video-caption">{title.split(" – ")[0]}</span>'+btn(ic('play'),f'Phát video: {title}','hs-play')+f'<span class="hs-duration">{duration}</span></div><h3>'+a(title)+f'</h3><p>HACOM Channel　|　{meta}</p></article>'
body+='</div>'+strip(['Video thực tế','Đánh giá khách quan','Hướng dẫn chi tiết','Cộng đồng công nghệ'],'Đăng ký ngay','Đăng ký kênh HACOM Channel','Cập nhật video mới nhất về sản phẩm, công nghệ và hướng dẫn sử dụng')
write(21,body,'#ed0028','hs-video-section')

# Section 22 — community activities.
pillars=[('Hỗ trợ giáo dục','Đồng hành cùng học sinh, sinh viên với nhiều chương trình ưu đãi, tài trợ thiết bị.','#ed0028','graduation-cap'),('Phát triển cộng đồng','Tổ chức workshop, sự kiện công nghệ, chia sẻ kiến thức, kết nối đam mê.','#0670ff','user-group'),('Vì môi trường xanh','Hướng tới tiêu dùng bền vững, thu gom và tái chế thiết bị điện tử.','#00a569','leaf'),('Chung tay vì xã hội','Tham gia các hoạt động thiện nguyện, hỗ trợ những hoàn cảnh khó khăn.','#8d2aee','heart')]
body='<div class="hs-community-top"><div class="hs-chapter-hero is-light">'+img(crop(22,'hero-artwork',(510,18,1240,355)),'Sinh viên cùng khám phá công nghệ tại HACOM','hs-chapter-art')+'<div class="hs-chapter-copy"><p class="hs-chapter-label">CHAPTER 18 / CỘNG ĐỒNG - TRÁCH NHIỆM XÃ HỘI</p><h1 id="s22-title" data-section-heading>HACOM<br><em>VÌ CỘNG ĐỒNG</em></h1><p>Công nghệ kết nối, cuộc sống tốt đẹp hơn.<br>HACOM luôn đồng hành cùng giáo dục, cộng đồng và thế hệ trẻ Việt Nam.</p>'+a('Tìm hiểu hoạt động cộng đồng '+ic('arrow-right'),'hs-cta')+'</div></div><div class="hs-pillars">'+''.join(f'<article style="--pillar:{color}">'+ic(g)+f'<div><h3>{t}</h3><p>{desc}</p></div></article>' for t,desc,color,g in pillars)+'</div></div><div class="hs-activities">'
activity=[('Workshop công nghệ cho sinh viên','Chia sẻ kiến thức - Truyền cảm hứng - Kết nối đam mê',(42,374,522,538)),('Tiếp sức đến trường','Trao cơ hội học tập - Kiến tạo tương lai',(540,374,1013,538)),('Hành động vì môi trường','Giảm rác thải điện tử - Lan tỏa lối sống xanh',(1031,374,1503,538)),('Hoạt động thiện nguyện','Lan tỏa yêu thương - Cùng xây dựng xã hội tốt đẹp hơn',(1522,374,2001,538))]
for i,(title,desc,box) in enumerate(activity):body+='<article>'+img(crop(22,f'activity-{i+1}',box),title)+a(f'<h3>{title}</h3><p>{desc}</p>'+ic('arrow-right'))+'</article>'
body+='</div><div class="hs-community-footer"><blockquote>“Công nghệ chỉ thực sự ý nghĩa<br>khi mang lại giá trị cho con người và cộng đồng.”<cite>— HACOM</cite></blockquote><div class="hs-community-metrics">'+''.join(f'<div><strong>{v}</strong><span>{t}</span></div>' for v,t in [('100+','Sự kiện cộng đồng mỗi năm'),('50.000+','Sinh viên được hỗ trợ tiếp cận công nghệ'),('10+','Chương trình vì môi trường bền vững'),('Nhiều hơn thế','Vì một xã hội tốt đẹp hơn cùng HACOM')])+'</div>'+a('Cùng HACOM<br>Kiến tạo giá trị bền vững '+ic('arrow-right'),'hs-cta')+'</div>'
write(22,body,'#ed0028','hs-community')

# Section 23 — customer mosaic, quote text remains HTML.
quotes=[('Trải nghiệm mua hàng rất tuyệt vời!','Hà Nội',(18,277,356,688)),('Nhân viên tư vấn rất nhiệt tình và chuyên nghiệp!','TP.HCM',(368,277,737,456)),('Build PC tại HACOM quá xịn!','Đà Nẵng',(748,277,1085,456)),('Sản phẩm chính hãng, dịch vụ rất tốt!','Hải Phòng',(1096,277,1433,456)),('HACOM luôn là lựa chọn hàng đầu của mình!','Cần Thơ',(1445,277,1756,456)),('Tư vấn rõ ràng, giao hàng nhanh!','Hà Nội',(368,541,662,715)),('Mua sắm tại HACOM... luôn yên tâm!','TP.HCM',(673,541,921,715)),('Giá tốt, nhiều ưu đãi!','Bình Dương',(932,541,1175,715)),('Trải nghiệm mua hàng rất chuyên nghiệp!','Hà Nội',(1186,541,1434,715)),('Dịch vụ hậu mãi rất chu đáo!','Đồng Nai',(1445,541,1756,715))]
body='<div class="hs-customer-head">'+heading(23,'CÙNG HÀNG TRIỆU KHÁCH HÀNG<br>KIẾN TẠO TRẢI NGHIỆM <em>TỐT HƠN</em>','Mỗi sản phẩm đến tay khách hàng là một câu chuyện.<br>Cảm ơn bạn đã tin tưởng và lựa chọn HACOM.','KHÁCH HÀNG HACOM')+a('Xem thêm hình ảnh '+ic('arrow-right'),'hs-cta')+'</div><div class="hs-customer-metrics">'+''.join('<div>'+ic(g)+f'<span><strong>{v}</strong>{t}</span></div>' for g,v,t in [('award','99%','Đánh giá tích cực'),('heart','Hàng ngàn','Câu chuyện hài lòng'),('camera','10.000+','Khoảnh khắc được chia sẻ'),('user-group','Luôn đồng hành','Trước - Trong - Sau mua hàng')])+'</div><div class="hs-gallery">'
for i,(quote,place,box) in enumerate(quotes):body+=f'<figure class="hs-gallery-{i+1}">'+img(crop(23,f'customer-{i+1}',box),'Khách hàng HACOM tại '+place)+f'<figcaption><blockquote>“{quote}”</blockquote><span>Khách hàng tại {place}</span></figcaption></figure>'
body+='</div><div class="hs-gallery-controls">'+btn(ic('chevron-left'),'Ảnh trước','hs-circle-button')+'<div class="hs-pagination"><span class="is-selected"></span>'+'<span></span>'*4+'</div>'+btn(ic('chevron-right'),'Ảnh tiếp theo','hs-circle-button')+'</div><p class="hs-tagline">CÙNG HACOM — NHIỀU HƠN CẢ MỘT SẢN PHẨM</p>'
write(23,body,'#ed0028','hs-customers')

# Section 24 — channel cards. Core copy, countdown and CTA are HTML.
channels=[('AI POWERED','CHƯA CHẮC<br><em>LAPTOP NÀO?</em>','Nhập ngân sách và nhu cầu sử dụng, AI HACOM sẽ gợi ý sản phẩm phù hợp chỉ trong vài giây.','Khởi động AI HACOM',['Gợi ý thông minh','Nhanh & chính xác','Sản phẩm phù hợp'],'#116eff',crop(20,'ai-channel',(1184,32,1351,140))),('SHOPEE MALL','DEAL TỐT<br>TRÊN <em>SHOPEE</em>','Mua hàng chính hãng, săn voucher độc quyền và nhận ưu đãi mới mỗi ngày từ HACOM Official Store.','Mua trên Shopee',['Shopee Mall chính hãng','Voucher độc quyền','Freeship toàn quốc'],'#ff591e',crop(24,'shopee-bag',(570,310,770,548))),('TIKTOK SHOP','DEAL HOT<br><em>TRÊN TIKTOK</em>','Xem livestream, săn voucher giới hạn và mua hàng chính hãng từ HACOM Official Store trên TikTok Shop.','Mua trên TikTok',['Livestream hằng ngày','Voucher độc quyền','Sản phẩm bán chạy'],'#ee0878',crop(24,'tiktok-phone',(949,322,1095,548))),('PC BUILDER','TỰ BUILD<br>BỘ PC <em>CỦA BẠN</em>','Tự chọn linh kiện, kiểm tra tương thích, dự đoán hiệu năng và chi phí trước khi đặt mua.','Thử PC Builder',['Kiểm tra tương thích','Dự đoán hiệu năng','AI gợi ý cấu hình'],'#00d183',crop(24,'builder-pc',(1275,300,1660,548))),('FLASH DEAL','FLASH SALE<br><em>SIÊU HOT</em>','Ưu đãi giới hạn thời gian cho Laptop, PC Gaming, linh kiện và phụ kiện công nghệ.','Săn Flash Deal',['Giá tốt mỗi ngày','Flash Sale theo giờ','Số lượng có hạn'],'#eebc36',crop(24,'flash-art',(1755,300,2037,446)))]
body='<h1 id="s24-title" data-section-heading class="sr-only">Khám phá các kênh mua sắm HACOM</h1><div class="hs-channels">'
for i,(label,title,desc,cta,perks,color,art) in enumerate(channels):body+=f'<article style="--card-accent:{color}"><p class="hs-channel-label">{label}</p><h3>{title}</h3><p>{desc}</p>'+img(art,'Artwork '+label,'hs-channel-art')+('<div class="hs-channel-countdown"><strong>12 : 36 : 52</strong><small>Giờ　 Phút　 Giây</small></div>' if i==4 else '')+a(cta+' '+ic('arrow-right'),'hs-channel-cta')+benefits(perks)+'</article>'
body+='</div>';write(24,body,'#00c0ff','hs-channel-section')

# Section 25 — footer: all showroom names, links and company information remain open.
showrooms=['HAI BÀ TRƯNG','ĐỐNG ĐA','HẢI PHÒNG','CẦU GIẤY','HÀ ĐÔNG 1','LONG BIÊN','TỪ SƠN','ĐÔNG ANH','BẮC GIANG','HÀ ĐÔNG 2','PHỦ LÝ','VINH','THÁI NGUYÊN','THANH HÓA','CẦU GIẤY 2','GIA LÂM (OCEAN PARK 1)','GIA LÂM 2','ĐỊNH CÔNG','THỦ ĐỨC, TP. HCM','GÒ VẤP, TP. HCM']
body='<div class="hs-footer-signup"><div class="hs-footer-logo">'+img('assets/images/section-1/hacom-logo.png','HACOM')+'<p>Công nghệ kết nối tương lai</p></div><div><p class="hs-eyebrow">ĐĂNG KÝ NHẬN TIN</p><h1 id="s25-title" data-section-heading>Nhận ưu đãi mới nhất <em>từ HACOM</em></h1><p>Đăng ký để nhận thông tin khuyến mãi, sản phẩm mới, tư vấn công nghệ và ưu đãi độc quyền.</p></div><div><div class="hs-inputrow"><label for="s25-email" class="sr-only">Email hoặc số điện thoại nhận ưu đãi</label><input id="s25-email" type="text" placeholder="Nhập email hoặc số điện thoại của bạn">'+btn('Đăng ký ngay '+ic('arrow-right'),cls='hs-cta')+'</div><label class="hs-checkbox"><input type="checkbox" checked> Tôi đồng ý nhận thông tin từ HACOM</label></div></div><div class="hs-showrooms"><figure>'+img(crop(25,'showroom',(0,111,526,412)),'Showroom HACOM với biển hiệu Laptop, PC, Workstation và Linh kiện')+'<figcaption>Hơn 22 showroom phục vụ bạn trên toàn quốc</figcaption></figure><div class="hs-showroom-content"><p class="hs-eyebrow">HỆ THỐNG SHOWROOM</p><h2>20 SHOWROOM HACOM TOÀN QUỐC</h2><p>Mạng lưới showroom công nghệ, PC Gaming, Laptop, AI PC và thiết bị CNTT của HACOM<br>với đội ngũ tư vấn, kỹ thuật viên và trung tâm hỗ trợ khách hàng trực tiếp.</p><div class="hs-showroom-stats"><span><b>20</b> Showroom</span><span><b>25</b> Năm phát triển</span><span><b>1.000.000+</b> Khách hàng</span><span><b>500+</b> Thương hiệu chính hãng</span></div><ol>'+''.join('<li>'+a(f'<b>{i+1:02}</b><span>HACOM - {t}</span>'+ic('plus'))+'</li>' for i,t in enumerate(showrooms))+'</ol>'+a('Xem bản đồ tất cả showroom '+ic('arrow-right'),'hs-outline-button')+'</div>'+img(crop(25,'vietnam-map',(1429,219,1534,397)),'Bản đồ Việt Nam với các điểm showroom HACOM','hs-footer-map')+'</div><div class="hs-footer-links"><div>'+img('assets/images/section-1/hacom-logo.png','HACOM','hs-footer-wordmark')+'<p>Công nghệ kết nối tương lai</p><p>HACOM là hệ thống bán lẻ công nghệ, PC Gaming, Laptop và thiết bị CNTT hàng đầu Việt Nam từ năm 2001.</p>'+a('Tìm hiểu về HACOM '+ic('arrow-right'),'hs-outline-button')+'</div>'
for title,links in [('Về HACOM',['Giới thiệu HACOM','Lịch sử phát triển','HACOM x Cộng đồng','Tuyển dụng','Tin tức']),('Hỗ trợ khách hàng',['Tra cứu đơn hàng','Hướng dẫn mua hàng','Hướng dẫn thanh toán','Hướng dẫn trả góp','Bảo hành','Khiếu nại']),('Chính sách',['Chính sách bảo hành','Chính sách giao hàng','Chính sách đổi trả','Chính sách doanh nghiệp','Chính sách dữ liệu cá nhân']),('Khuyến mại',['Flash Sale','Laptop Sale','PC Gaming Sale','Mã giảm giá','Khuyến mại theo hãng'])]:body+=f'<nav aria-label="{title}"><h3>{title}</h3><ul>'+''.join('<li>'+a(t)+'</li>' for t in links)+'</ul></nav>'
body+='</div><h2 class="hs-footer-category-title">Khám phá danh mục sản phẩm</h2><div class="hs-footer-categories">'
for i,(title,links,art) in enumerate([('Laptop',['Laptop AI','Laptop Gaming','Laptop Văn phòng','MacBook'],'assets/images/section-1/laptop-artwork.webp'),('PC',['PC Gaming','PC AI','Workstation','Mini PC'],'assets/images/sections/s24-builder-pc.webp'),('Linh kiện',['VGA','CPU','Mainboard','RAM','SSD'],'assets/images/sections/s8-product-3.webp'),('Màn hình',['OLED Monitor','Gaming Monitor','Đồ Họa'],'assets/images/sections/s9-product-1.webp'),('Gaming Gear',['Chuột','Bàn phím','Tai nghe','Ghế Gaming'],'assets/images/sections/s11-product-3.webp')]):body+='<article><h3>'+title+'</h3><ul>'+''.join('<li>'+a(t)+'</li>' for t in links)+'</ul>'+img(art,title)+a('Xem ngay '+ic('arrow-right'))+'</article>'
body+='</div><div class="hs-footer-partners"><div><h3>Kết nối cùng HACOM</h3><p>Theo dõi HACOM trên các kênh mạng xã hội để cập nhật tin tức, video review, khuyến mãi và cộng đồng công nghệ.</p><div class="hs-socials">'+''.join(a(t) for t in ['Facebook','YouTube','TikTok','Instagram','Zalo'])+'</div><p>500.000+ Followers　　100.000+ Subscribers</p></div><div><h3>Thanh toán an toàn, tiện lợi</h3><div class="hs-payment-badges">'+''.join('<span>'+t+'</span>' for t in ['VISA','Mastercard','VNPAY','OnePay','MoMo','Chuyển khoản Ngân hàng'])+'</div></div><div><h3>Chứng nhận & đối tác</h3><div class="hs-payment-badges">'+''.join('<span>'+t+'</span>' for t in ['BỘ CÔNG THƯƠNG ĐÃ ĐĂNG KÝ','DMCA PROTECTED','Microsoft Partner','ASUS','acer','intel'])+'</div></div></div><div class="hs-company"><div><h3>CÔNG TY CỔ PHẦN ĐẦU TƯ CÔNG NGHỆ HACOM</h3><p>Thành lập: 2001</p><p>Trụ sở: 129-131 Lê Thanh Nghị, Hai Bà Trưng, Hà Nội</p></div><div>'+ic('phone-volume')+'<span>Hotline<strong>1900 1903</strong></span></div><div>'+ic('envelope')+'<span>Email<strong>info@hacom.vn</strong></span></div><div>'+ic('globe')+'<span>Website<strong>www.hacom.vn</strong></span></div><div>'+ic('leaf')+'<span>Vì một tương lai<br>xanh hơn</span></div></div><div class="hs-copyright"><span>© 2001 - 2027 HACOM</span><span>Hệ thống bán lẻ Laptop, PC Gaming, AI PC và thiết bị công nghệ hàng đầu Việt Nam.</span><span>22 Showroom toàn quốc.</span><strong>HACOM</strong><span>Cùng công nghệ<br>kiến tạo giá trị tốt đẹp hơn</span></div>'
write(25,body,'#ed0028','hs-footer')

# Preserve approved sources 1 and7. New sections are drafted, not approved.
p=ROOT/'src/sections.manifest.json';manifest=json.loads(p.read_text(encoding='utf-8'));manifest['reviewMode']='combined'
for s in manifest['sections']:
    s['status']='approved' if s['number'] in [1,7] else 'in_review'
    if s['number']==1:s['approval']={'evidence':'Người dùng: tốt lắm, triển khai toàn bộ và review chung sau chỉnh menu.'}
p.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(ROOT/'docs/specs/asset-manifest.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
for n in [2,3,4,5,6,*range(8,26)]:
    p=ROOT/f'docs/specs/section-{n}.md';text=p.read_text(encoding='utf-8').split('\n## Triển khai review chung')[0];text+='\n## Triển khai review chung\n\nNguồn HTML đã dựng trong src/sections; preview độc lập và trang index ghép đủ 25 section. Trạng thái in_review, chưa được người dùng nghiệm thu. Asset chi tiết/tọa độ/kích thước: asset-manifest.json. Artwork được trích từ thiết kế, chữ/giá/CTA là HTML; logo có file gốc được sao chép cục bộ, các wordmark còn thiếu dùng chữ.\n';p.write_text(text,encoding='utf-8')
print(f'Prepared 23 static sections and {len(records)} clean artwork assets.')
